#!/bin/bash
node contract addEntry LinkedList null 42 "Eva"
node contract addEntry LinkedList null 23 "Julian"
node contract addEntry LinkedList null 34 "Hal"
node contract addEntry LinkedList null 12 "Julian"
node contract addEntry LinkedList null 45 "Eva"
node contract addEntry LinkedList null 27 "Hal"
node contract addEntry LinkedList null 57 "Hal"
node contract addEntry LinkedList null 33 "Eva"
node contract addEntry LinkedList null 23 "Julian"
node contract addEntry LinkedList null 85 "Hal"
node contract addEntry LinkedList null 26 "Hal"
node contract addEntry LinkedList null 23 "Julian"
node contract addEntry LinkedList null 67 "Eva"
